### ISSUE TITLE
nullptr error

### ISSUE THREAD

**Issue by tiannahaha** [FZzzz/SnowSimulation#1]
Hello, I found that the project uses GPU cuda calculation by default. 
However, when I didn't use cuda, I found that the `ComputeDensity( )` function reported an error of "nullptr". Is it the problem of `m_neighbor_searcher`or other? Can u give a help?

**Comment by FZzzz** [comment]
1. CUDA is essential to this project. Be sure to build this with the correct CUDA version
2. Please point out which line of code you get the nullptr.

**Comment by tiannahaha** [comment]
I found that the normal process is to run `StepCUDA()`. 
I also want to see the effect of `Step()`, so I commented it out the line define_[ USE_ CUDA_ ](https://github.com/FZzzz/SnowSimulation/blob/056498f43826a712b9f9386e083a544fe332a987/GLFWApp.cpp#L595)and an error is reported.
This is the error report:
![1676113947132](https://user-images.githubusercontent.com/50192906/218255073-f1ce5bf0-d3ae-481f-b984-305cb55a243a.jpg)

[This line](https://github.com/FZzzz/SnowSimulation/blob/056498f43826a712b9f9386e083a544fe332a987/Simulation.cpp#L401) is the previous layer of the call stack when I check the error.

**Comment by FZzzz** [comment]
It won't be possible to run things properly with Step(). I didn't implement anything related to snow simulation with it. That part of code is very old which comes from my other project for fluid simulation. Sorry for the confusion, I will remove them if I have extra time to work on this.

**Comment by tiannahaha** [comment]
Oh, well, that means this project is only iterative with `stepcuda()`, right?

**Comment by FZzzz** [comment]
Yes, you are right.

**Comment by tiannahaha** [comment]
Ok, thanks for your reply:)

**Comment by FZzzz** [comment]
You're welcome. Just removed some of them. Should be easier to trace the code. Thanks for letting me know this issue.

**Comment by tiannahaha** [comment]
> You're welcome. Just removed some of them. Should be easier to trace the code. Thanks for letting me know this issue.

Hello, I am trying to understand the `snow_simulation()` in `StepCuda()`. 
I would like to further understand the principle of `snow_simulation()` through single step debugging, but I found that single step debugging does not call this function. 
Is there a problem with my debugging method? I hope to receive your guidance~

**Comment by FZzzz** [comment]
First of all, you need to know the kernel functions are executed on GPU, they can't be debugged through the normal process you debug CPU code. A walkaround is - put printf inside the kernel functions and observe the values. Otherwise, you will have to use the Nvidia's profiler to debug your CUDA program (However, I won't suggest you to do this. Simply because there are too many particles).

If you want to know the flow - just check snow_simulation. It should give you enough hint to understand this program without touching those implementation details of the kernel functions.

**Comment by tiannahaha** [comment]
Oh I see. Thanks for your generous help!
